### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ac0d3r** [ac0d3r/Hyuga#32]
# 关于部署
## 部署
Hyuga 通过github action 自动发布，使用 embed 打包好前端资源文件，所以部署特别简单：

1. 准备一个域名，如 `hyuga.icu`，准备一台vps，如公网ip `1.1.1.1` 。
2. 在 cloudflare 中添加 hyuga.icu，并按照提示修改域名 DNS 服务器。
3. 在cloudflare dns 那里添加两条记录：
    ![image](https://github.com/ac0d3r/Hyuga/assets/26270009/de428382-e125-4d55-97b7-36dc93130a79)
    
    - `ns.hyuga.icu` → `1.1.1.1`
    - `zznq.hyuga.icu` NS → `ns.hyuga.icu`
4. 下载 hyuga：[Hyuga releases](https://github.com/ac0d3r/Hyuga/releases/tag/v4.0.2)
5. 编辑配置文件 config.toml ，修改dns 、github 等
    ```toml
    ...
    [oob]
        [oob.dns]
            main = "zznq.hyuga.icu"
            ip = "1.1.1.1"
            ns = ["ns.hyuga.icu"]
        [oob.jndi]
            address = ":233"
            limit = 1000
    
    [web]
        address = "localhost:8080"
        [web.github]
            client-id = "xxx"
            client-secret = "xxxxxxxx"
    ```
    
6. 运行 ./hyuga -config config.toml
### 支持https部署
7. 安装 caddy  [https://caddyserver.com/docs/install](https://caddyserver.com/docs/install)
8. 配置 `/etc/caddy/Caddyfile` 然后重启 systemctl restart caddy
    
    ```
    zznq.hyuga.icu {
        reverse_proxy localhost:8080
    }
    :80 {
        reverse_proxy localhost:8080
    }
    ```

# 其他
可以问题都可以此 issue 下讨论！

### 其他
可以关注下[巴斯.zznQ](https://blog.macoder.tech/)的公众号：
![image](https://github.com/ac0d3r/Hyuga/assets/26270009/5cc344f7-55e5-4b88-bfd4-616b40ee4c35)

**Comment by ac0d3r** [comment]
## 自定义部署之注册 Github Oauth app
上面忘记提了

1. 登录 Github
2. https://github.com/settings/developers
3. 新建 Oauth app

<img width="1148" alt="image" src="https://github.com/ac0d3r/Hyuga/assets/26270009/ab1a4ab7-5e2c-43c6-b1c3-a85dda5aee4d">

4. 配置 **Authorization callback URL**，将此处域名替换为自定义的域名：
<img width="517" alt="image" src="https://github.com/ac0d3r/Hyuga/assets/26270009/54a7b867-882b-49e8-830a-5bcf81888171">


5. 拷贝 **Client ID** & **Client secrets**
6. 配置 `config.toml` `web.github`

```toml
...
[web]
    address = "localhost:8080"
    [web.github]
        client-id = "{{Client ID}}"
        client-secret = "{{Client secrets}}"
```
